import * as React from "react";
import {
    DataGrid,
    GridColDef,
    GridValueGetterParams,
    GridRenderCellParams,
    GridActionsCellItem,
    zhCN,
} from "@mui/x-data-grid";
import Button from "@mui/material/Button";

const columns: GridColDef[] = [
    {
        field: "rowIndex",
        headerName: "序号",
        sortable: false,
        hideable: false,
        filterable: false,
    },
    {
        field: "niche_code",
        headerName: "商机编号",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: "AccountID",
        headerName: "AccountID",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: "MRN",
        headerName: "MRN",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: "name",
        headerName: "客户姓名",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: "NicheStatus",
        headerName: "订单状态",
        sortable: false,
        hideable: false,
        filterable: false,
        width: 70,
    },

    // {
    //     field: "NicheStatus",
    //     headerName: "创建人",
    //     sortable: false,
    //     hideable: false,
    //     filterable: false,
    //     width: 70,
    // },

    {
        field: "create_time",
        headerName: "创建时间",
        sortable: false,
        hideable: false,
        filterable: false,
        width: 70,
    },

    {
        field: "product_name",
        headerName: "产品",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    // {
    //     field: "id",
    //     headerName: "产品金额",
    //     sortable: false,
    //     hideable: false,
    //     filterable: false,
    //     width: 70,
    // },

    {
        field: "ChannelType",
        headerName: "渠道类型",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: " Child_ChannelName",
        headerName: "渠道名称",
        sortable: false,
        hideable: false,
        filterable: false,
    },

    {
        field: "actions",
        headerName: "操作",
        renderCell: (params: GridRenderCellParams<Date>) => (
            <>
                <Button
                    variant="contained"
                    size="small"
                    onClick={() => {
                        console.log("params", params);
                    }}
                >
                    Open
                </Button>
            </>
        ),
    },
];

const rows = [
    {
        rowIndex: 1,
        niche_id: 1,
        order_id: 1,
        customer_id: 1,
        niche_code: "220700001",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 2,
        ChannelType: "第三方平台",
        Child_ChannelId: 21,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 15:01:43",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-14 17:21:01",
        hospital_id: 3,
        hospital_name: "上海怡合览海门诊部",
    },
    {
        rowIndex: 2,
        niche_id: 1,
        order_id: 2,
        customer_id: 1,
        niche_code: "220700001",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 15:01:58",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-16 11:43:49",
        hospital_id: 3,
        hospital_name: "上海怡合览海门诊部",
    },
    {
        rowIndex: 3,
        niche_id: 6,
        order_id: 3,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 1,
        ChannelType: "第三方平台",
        Child_ChannelId: 2,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 18:25:46",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-16 10:11:49",
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 4,
        niche_id: 6,
        order_id: 4,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 2,
        ChannelType: "第三方平台",
        Child_ChannelId: 11,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 18:25:46",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-14 14:12:33",
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 5,
        niche_id: 6,
        order_id: 5,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 1,
        ChannelType: "第三方平台",
        Child_ChannelId: 2,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 18:26:06",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-14 14:18:17",
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 6,
        niche_id: 6,
        order_id: 6,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 18:26:06",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 7,
        niche_id: 6,
        order_id: 7,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:17:01",
        update_user: 20,
        UpdateUser_Name: "系统管理员",
        update_time: "2022-07-14 14:18:24",
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 8,
        niche_id: 6,
        order_id: 8,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:17:01",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 9,
        niche_id: 6,
        order_id: 9,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:17:17",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 10,
        niche_id: 6,
        order_id: 10,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:17:17",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 11,
        niche_id: 6,
        order_id: 13,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:22:29",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 12,
        niche_id: 6,
        order_id: 14,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:22:29",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 13,
        niche_id: 6,
        order_id: 15,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:29:30",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 14,
        niche_id: 6,
        order_id: 16,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "3|Package",
        product_name: "水光热玛吉组合套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 8800,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:29:30",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
    {
        rowIndex: 15,
        niche_id: 6,
        order_id: 17,
        customer_id: 1,
        niche_code: "220700002",
        AccountID: "C00000001",
        MRN: null,
        name: "顾增国",
        phone: "18721595343",
        product_id: "1|Package",
        product_name: "水光套餐",
        channel_id: 3,
        ChannelType: "第三方平台",
        Child_ChannelId: 6,
        Child_ChannelName: "天猫",
        total_amount: 2550,
        line_flag: "OFFLINE",
        line_flag_desc: "线下",
        OrderStatus: "进行中",
        create_user: 20,
        CreateUser_Name: "系统管理员",
        create_time: "2022-07-06 20:29:58",
        update_user: null,
        UpdateUser_Name: null,
        update_time: null,
        hospital_id: 2,
        hospital_name: "上海览海门诊部",
    },
];

export default function DataTable() {
    return (
        <div style={{ height: 500, width: "100%" }}>
            <DataGrid
                localeText={zhCN.components.MuiDataGrid.defaultProps.localeText}
                getRowId={(row) => row.rowIndex}
                rows={rows}
                columns={columns}
                checkboxSelection
                onPageChange={(page) => {
                    console.log("page", page);
                }}
            />
        </div>
    );
}
